---
- name: Add mongo apt key
  apt_key:
    id: 0C49F3730359A14518585931BC711F9BA15703C6
    keyserver: 'hkp://keyserver.ubuntu.com:80'
    state: present

- name: Add mongo apt repo
  apt_repository:
    repo: 'deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse'
    state: present
